name: Run Checkov code analysis

on:
  - pull_request
  - push

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true